sudo: required

services:
  - docker

env:
  global:
    - REPO=unpublished/build-orfox

script:
  - docker build -f Dockerfile -t $REPO .
  - docker images

after_success:
  - docker tag $REPO $REPO:$TRAVIS_BRANCH
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $REPO
  - docker logout